#	$BASE style.c,v 0.0 2021/06/29 02:18:05 moatx Exp $		

include ../../config.mk

all:
	make -C i386
	make -C boot

#grub:
#	make -C boot grub
#	make -C i386

indent:
	make -C i386 indent


.PHONY: all indent grub
